apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: maven-web-app-deploy-k8/maven-web-app-deploy-k8/edsam22/maven-web-app:63-ecc19a149d450c06c6d143e8c200c2527afe6ac6
        ports:
        - containerPort: 8080
